### PR TITLE
RTFHandler fixes with focus in unicode and characters set

### PR DESCRIPTION
**Pull request by javierag**
Several fixes:
 - Better parsing of font table
 - When using a font, switch to its character set
 - Correct parsing of escaped characters
 - Unicode character command word support for unicode characters greater than 32767

### CODE REVIEW

**Comment by javierag** [comment]
One monet I have detected a little regression

**Comment by javierag** [comment]
Well, it was a sleeping error triggered by other changes. Now fixed.

**Comment by javierag** [comment]
:no_good:   Dont review this yet

**Comment by sixstone-qq** [comment]
I agree with @blaxter it will help for traceability and identity

**Comment by javierag** [comment]
Ok, this is ready. Two things:

- I don't know what is the original rationale for using NSMapTable instead of NSDictionary. At first sight we neither add more keys or use any of the additonal features of NSMapTable

As for rebasing with jgarcia/unittest-working there is a huge rebase and it made me wary. Maybe cherry picking could do the trick?. In that case, it will suffice with the commits of Mar 12 and Mar 13 or others are needed?. I am taking about this timeline -> https://github.com/zentyal/sogo/commits/jgarcia/unittest-working

**Comment by blaxter** [comment]
The rebase was huge because the branch is quite old since creation but a merge was almost clean without conflicts

**Comment by javierag** [comment]
Ok, i will try the merge then

**Comment by sixstone-qq** [comment]
@javierag It does not compile:
```
./obj/sogo-tests.obj/../../OpenChange/RTFHandler.m.o:(.rodata+0x1260): multiple definition of `ansicpg874'
./obj/sogo-tests.obj/../../OpenChange/RTFHandler.m.o:(.rodata+0x1260): first defined here
./obj/sogo-tests.obj/../../OpenChange/RTFHandler.m.o:(.rodata+0x1800): multiple definition of `__objc_class_name_RTFColorTable'

```

**Comment by javierag** [comment]
Sorry, bad merge

**Comment by javierag** [comment]
I will make and one more change to accommodate a parsing error that i have seen in a crash

**Comment by javierag** [comment]
Ok, ready to review.

**Comment by javierag** [comment]
The cases where set aping the existent code. All the unit test classes use 'test_foo'.

In my opinion, the 'test_' should be kept but only for the methods which will interpreted as test cases by the test runner. ('test' prefix and not having a ':' in ther iname).
I would remove it from helper methods.

Deal?

**Comment by sixstone-qq** [comment]
@javierag deal

File: OpenChange/RTFHandler.m [hunk 1]
```diff
@@ -282,17 +282,28 @@ - (id) init
     {
       
     }
+
+  charset = 1; // value for default charset
```
Comment (blaxter) [inline OpenChange/RTFHandler.m]: What do you think of some `#define DEFAULT_CHARSET 1`? magic numbers are evil

File: OpenChange/RTFHandler.m [hunk 2]
```diff
@@ -282,17 +282,28 @@ - (id) init
...
   [super dealloc];
 }
 
+- (NSString *) description
+{
+  NSString *description;
+  description = [NSString stringWithFormat:
+                          @"%u name=%@ family=%@ charset=%u pitch=%u\n",                
+                          index, name, family, charset, pitch
+                 ];
```
Comment (blaxter) [inline OpenChange/RTFHandler.m]: weird \n here

File: OpenChange/RTFHandler.m [hunk 3]
```diff
@@ -700,9 +960,239 @@ - (void) parsePicture
...
+    return;
+
+  if (formattingOptions->color_index >= 0)
+    {
+      [self->_html appendBytes: "</font>"  length: 7];
+    }
+
+  formattingOptions->color_index = arg;
+
+  v = malloc(23*sizeof(char));
```
Comment (blaxter) [inline OpenChange/RTFHandler.m]: malloc + memset is the same as calloc

File: OpenChange/RTFHandler.m [hunk 4]
```diff
@@ -378,26 +405,149 @@ - (RTFColorDef *) colorDefAtIndex: (unsigned int) theIndex
...
 {
-  if ((self = [super init]))
-    {
-      ASSIGN(_data, theData);
-      _bytes = (char *)[_data bytes];
-      _len = [_data length];
-      _current_pos = 0;
-      
-      _charsets = NSCreateMapTable(NSObjectMapKeyCallBacks, NSNonOwnedPointerMapValueCallBacks, 10);
+      _charsets = NSCreateMapTable(NSObjectMapKeyCallBacks, NSNonOwnedPointerMapValueCallBacks, 23);
```
Comment (blaxter) [inline OpenChange/RTFHandler.m]: Any reason to use this functions instead of NSDictionary and other classes? (check Codepages.m for similar code to this)

**Comment by javierag** [comment]
This need firstly to merge this branch: https://github.com/zentyal/sogo/pull/209

**Comment by javierag** [comment]
Mangle it is used sometimes in software to denote a very forceful manipulation, think in the mangle table of iptables.
This method is included only for inject values to ease testing.

**Comment by infosite** [comment]
Hi, excuse my ignorance but I can not find a way to edit files RTFHandler.me RTFHandler.l
How can I do?

Thank you

**Comment by javierag** [comment]
You should do your clone of this GIT repository and then do they changes you want.
Here you have pointers for information about git and github: https://help.github.com/articles/good-resources-for-learning-git-and-github/

File: OpenChange/RTFHandler.m [hunk 5]
```diff
@@ -378,26 +407,149 @@ - (RTFColorDef *) colorDefAtIndex: (unsigned int) theIndex
...
+  CW_PAR,
+  CW_PICT,
+  CW_SOFTLINE,
+  CW_STRIKE,
+  CW_STYLESHEET,
+  CW_TAB,
+  CW_U,
+  CW_UL,
+  CW_ULNONE
+} CW_ID;
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: Why do use UPPER_CASE for a type definition? Shouldn't it be `CwId` or `CwIdType`?

File: OpenChange/RTFHandler.m [hunk 6]
```diff
@@ -378,26 +407,149 @@ - (RTFColorDef *) colorDefAtIndex: (unsigned int) theIndex
...
+  FONTCW_FCHARSET,
+  FONTCW_FDECOR,
+  FONTCW_FMODERN,
+  FONTCW_FNIL,
+  FONTCW_FPRQ,
+  FONTCW_FROMAN,
+  FONTCW_FSCRIPT,
+  FONTCW_FSWISS,
+  FONTCW_FTECH
+} FONTCW_ID;
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: The same applies here. `FontCW`?

File: OpenChange/RTFHandler.m [hunk 7]
```diff
@@ -529,109 +763,137 @@ - (RTFColorTable *) parseColorTable
 //
 // We receive the full string.
 //
+
+
 - (RTFFontTable *) parseFontTable
 {
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: To follow the same standards that Objective C has, using `[self parse]` would be great. See the following link for details:
https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSXMLParser_Class/index.html#//apple_ref/occ/instm/NSXMLParser/parse

File: OpenChange/RTFHandler.m [hunk 8]
```diff
@@ -529,109 +763,137 @@ - (RTFColorTable *) parseColorTable
...
         {
-          if (isalnum(*_bytes))
-            [fontName appendFormat: @"%c", *_bytes]; 
+          if (level == 2 && isalnum(*_bytes))
+            {
+              // we assume this is the fontname
+              // there is no limit length but we took 100
+              // as protection
+              const char *delim = strpbrk(_bytes, ";{}\\");
+              unsigned int fontnameLen = delim - _bytes;
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: If `delim` is NULL, this substraction will lead to incorrect values.

**Comment by javierag** [comment]
Instructions for testing:


What to test:
There are several fixes here and changes that affect the RTF parsing. However I think we should manually test the errors that motivated this work:

    test on the notes/description field of contacts and events
    test with english text
    test with text with does not use a latin alphabet
    test with text which contains ñáéíóúÁÉÍÓÚ

Remember that the parsing is not complete so an error could be an previous existent error and in that case I should be left for later.

File: OpenChange/RTFHandler.m (hunk 7 above)
Comment (javierag) [inline OpenChange/RTFHandler.m]: Neither is a 'parse standard', nor we have a event-driven parser and this is not  a library for third-parties. Please, focus on our product.

File: OpenChange/RTFHandler.m (hunk 8 above)
Comment (javierag) [inline OpenChange/RTFHandler.m]: That was a good catch, moreover the rtf should be very bad formed to delim == NULL so it will not be detected by the tests.

File: OpenChange/RTFHandler.m (hunk 4 above)
Comment (javierag) [inline OpenChange/RTFHandler.m]: As I told in my general comment, this is inherited code and I can only guess. I think the reason is that NSMapTable is better suited for storing arbitrary pointer or no-object data.

File: OpenChange/RTFHandler.m (hunk 5 above)
Comment (javierag) [inline OpenChange/RTFHandler.m]: I have changed the typedef to lowercase

File: OpenChange/RTFHandler.m (hunk 4 above)
Comment (blaxter) [inline OpenChange/RTFHandler.m]: :+1:

**Comment by blaxter** [comment]
:ok_hand:

File: OpenChange/RTFHandler.m [hunk 9]
```diff
@@ -531,107 +763,140 @@ - (RTFColorTable *) parseColorTable
...
+                  // no delimiter found, we skip to next characters
                   ADVANCE;
+                  continue;
                 }
-              while (cc != 0);
-
-              // move back our buffer;
-              REWIND;
+              fontnameLen = delim - _bytes;
+              // only valid if the delimator is a correct ';'
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: Typo: `delimiter`?

File: OpenChange/RTFHandler.m [hunk 10]
```diff
@@ -531,107 +763,140 @@ - (RTFColorTable *) parseColorTable
...
+              if (delim && *delim == ';')
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: The NULL check is not longer required.

File: OpenChange/RTFHandler.m [hunk 11]
```diff
@@ -531,107 +763,140 @@ - (RTFColorTable *) parseColorTable
...
+                {
+                  // there is no explicit limit length but we took 100
+                  // as protection
+                  if (delim && fontnameLen <= FONTNAME_LEN_MAX)
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: The NULL check here is no longer required.

File: OpenChange/RTFHandler.m [hunk 12]
```diff
@@ -700,9 +965,238 @@ - (void) parsePicture
...
+  NSString *key;
+  const unsigned short *res;
+
+  if (!hasArg)
+    return;
+  key = [NSString stringWithFormat: @"anscicpg%i", arg];
+  res =  NSMapGet(_charsets, key);
+  if (res)
+    *out_default_char = res;
+}
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: Just guessing... Why don't you return here the `const unsigned short` having 0 as on error value?

File: OpenChange/RTFHandler.m [hunk 13]
```diff
@@ -700,9 +965,238 @@ - (void) parsePicture
...
+      // RTF badformed? We don't know about that font (arg index not found).
+      // Anyhow, we still open the html tag because in the future
+      // we will close it (e.g. when new font is used).
+      v = calloc(7, sizeof(char));
+      sprintf(v, "<font>");
+    }
+
+  if (fontInfo && fontInfo->charset)
+    {
+      if (fontInfo->charset == 1)
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: You can use here the define `DEFAULT_CHARSET`

File: OpenChange/RTFHandler.m [hunk 14]
```diff
@@ -1024,17 +1430,31 @@ - (NSMutableData *) parse
...
       else
         {
-          // We avoid appending NULL bytes
-          if (*_bytes)
-            [_html appendBytes: _bytes  length: 1];
+          c = *_bytes;
+          // We avoid appending NULL bytes or endlines
+          if (c && (c != '\n')) 
+            {
+              if (c < 0x7f)
```
Comment (sixstone-qq) [inline OpenChange/RTFHandler.m]: We could have this as a define as well to avoid magic number with a name like `MAX_ASCII_CHAR`?

**Comment by sixstone-qq** [comment]
Although I don't understand the usage of `static inline` having `*self` as first parameter having methods to dispatch, I can live with that. Other than that, once the minor comments are reviewed by @javierag to accept or reject them, I'll merge it.

File: OpenChange/RTFHandler.m (hunk 12 above)
Comment (javierag) [inline OpenChange/RTFHandler.m]: This is for symmetry with the other functions called from the parse switch. A lot of them modify more than one variable so we dont use return value.

**Comment by javierag** [comment]
As suggested before there are two ways to do this use a switch or instead returning the command word returning a function pointer or a function object.
It seemed to me that the switch was speedir just for avoiding a call (static inline is not a call); maybe I am wrong and that a function pointer can be faster.
Anyway, using a half-way solution, switch+method call, would be to use the downsides of both solutions.

**Comment by blaxter** [comment]
Premature optimization is the root of all evil.

The inline modifier nowadays in 2015 where we have really smart compilers (at least smarter than me, that's for sure) doesn't really matter, the compiler will inline functions without us telling it so and can also ignore our inline suggestions. To worry about performance because the overhead of a function call is the least of our problems, it will never be the real bottleneck. But the whole file needs a huge refactorization so I don't mind to merge this and fix it in the future.

**Comment by sixstone-qq** [comment]
Korean characters are not working. The following event description in Outlook:
```
English text with no typos.

Россия является матерью всех Foo

한국은 지금 2로 나누어 져 있지만 하나를해야한다
```
is being shown as this in SOGo Webmail:
```
English text with no typos.

Россия является матерью всех Foo

ꪣÇÑ튒±¹뢿Àº 똿Áö퇷±Ý 2잣·Î 콧³ª췻´©멋¾î 럇Á® 롷ÀÖ똿Áö옳¸¸ ꪧÇÏ콧³ª욃¸¦ꪋÇØ몃¾ßꪣÇÑ촛´Ù
```
Is this the expected behaviour @javierag ?

**Comment by javierag** [comment]
I think the korean error is due that is a multibyte windows codepage. It wa not supporter and I hvent added support.
I suggest we implement it in another task, (nxext sptrint perhaps?)
